name = "ai-gateway-worker"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ai_gateway_db"
database_id = "dbf42c03-b429-4ed8-b54c-f016524a240b"

[[kv_namespaces]]
binding = "CACHE"
id = "b6f208541f0e4d3c9c359455f702cd43"

[vars]
ENVIRONMENT = "development"
